language: python

python: 3.6

services:
    - docker

cache:
    - pip
    - npm

before_install:
    - docker-compose -f .travis-docker-compose.yml up -d

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install && cd ..

script:
    - cd server && flake8 && nosetests && cd ..
    - cd client && node --max_old_space_size=4098 ./node_modules/.bin/grunt build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..
