logstash:
  extends:
    file: common.yml
    service: logstash
  links:
  - elastic

mongodb:
  extends:
    file: common.yml
    service: mongodb

redis:
  extends:
    file: common.yml
    service: redis

kibana:
  extends:
    file: common.yml
    service: kibana
  links:
  - elastic
  ports:
  - "5601:5601"

elastic:
  extends:
    file: common.yml
    service: elastic

postfix:
  extends:
    file: common.yml
    service: postfix

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
   - pubapi
  ports:
   - "443:443"
   - "80:80"

pubapi:
  extends:
    file: common.yml
    service: pubapi
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
