rest: hypercorn -c file:hypercorn_config.py wsgi:application
wamp: python3 -u ws.py
work: celery -A worker worker
beat: celery -A worker beat
capi: hypercorn -c file:hypercorn_config.py -w "${CAPI_WORKERS:-2}" content_api.wsgi:application
papi: hypercorn -c file:hypercorn_config.py -w "${PAPI_WORKERS:-2}" prod_api.wsgi:application
#highcharts: python3 -u -m analytics.reports.highcharts_server
