name: "CI"

on:
  [push, pull_request]

jobs:

  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server
    
    services:
      redis:
        image: redis:alpine
        ports:
            - "6379:6379"

      mongo:
        image: mongo:4
        ports:
            - "27017:27017"

      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        ports:
            - "9200:9200"
        env:
          discovery.type: single-node

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: server/requirements.txt

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

      - name: pip install
        run: |
            python -m pip install --upgrade pip wheel setuptools
            pip install -r dev-requirements.txt

      - run: flake8
      - run: nosetests tests
      - run: mypy .
      - run: python manage.py app:initialize_data

  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - run: npm ci || npm install
      - run: npm run build
