name: "CI"

on:
  [push, pull_request]

jobs:

  server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: apt-get
        run: sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

      - name: docker-compose
        run: docker-compose -f ../.travis-docker-compose.yml up -d

      - name: cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-
            
      - name: pip install
        run: |
            python -m pip install --upgrade pip wheel setuptools
            pip install -r dev-requirements.txt

      - name: flake8
        run: flake8

      - name: nosetests
        run: nosetests tests

      - name: mypy
        run: mypy .

      - name: initialize data
        run: python manage.py app:initialize_data

  client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm
            ${{ runner.os }}-

      - name: npm ci
        run: npm ci

      - name: grunt build
        run: node --max_old_space_size=4098 ./node_modules/.bin/grunt build
